In [11]:
!pip -q install pandas numpy tqdm sentence-transformers faiss-cpu huggingface_hub rapidfuzz

In [12]:
from huggingface_hub import login

login()

In [13]:
import os
import re
import math
import json
import glob
import shutil
import numpy as np
import pandas as pd

from pathlib import Path
from tqdm import tqdm
from rapidfuzz import fuzz
from huggingface_hub import list_repo_files, hf_hub_download
from sentence_transformers import SentenceTransformer
import faiss

REPO_ID = "databricks/officeqa"
YEARS = [2022, 2023, 2024, 2025]
K = 5

PROJECT_DIR = Path("/content/financial_rag_officeqa")
DATA_DIR = PROJECT_DIR / "data"
DOC_DIR = DATA_DIR / "docs"
RESULTS_DIR = PROJECT_DIR / "results"

for folder in [PROJECT_DIR, DATA_DIR, DOC_DIR, RESULTS_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

print("Project folder:", PROJECT_DIR)
print("Years used:", YEARS)

Project folder: /content/financial_rag_officeqa
Years used: [2022, 2023, 2024, 2025]

In [14]:
files = list_repo_files(REPO_ID, repo_type="dataset")

print("Total files found:", len(files))
print("First 30 files:")
for f in files[:30]:
    print(f)

Total files found: 2105
First 30 files:
.gitattributes
.gitignore
.hfignore
LICENSE-APACHE
LICENSE-CC-BY-SA
NOTICE
README.md
officeqa_full.csv
officeqa_pro.csv
treasury_bulletin_pdfs/treasury_bulletin_1939_01.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_02.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_03.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_04.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_05.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_06.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_07.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_08.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_09.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_10.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_11.pdf
treasury_bulletin_pdfs/treasury_bulletin_1939_12.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_01.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_02.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_03.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_04.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_05.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_06.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_07.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_08.pdf
treasury_bulletin_pdfs/treasury_bulletin_1940_09.pdf

In [15]:
csv_candidates = [f for f in files if "officeqa_full" in f.lower() and f.lower().endswith(".csv")]

print("CSV candidates:", csv_candidates)

if not csv_candidates:
    raise FileNotFoundError("Could not find officeqa_full.csv. Check dataset access on Hugging Face.")

officeqa_csv_path = hf_hub_download(
    repo_id=REPO_ID,
    filename=csv_candidates[0],
    repo_type="dataset"
)

qa_df = pd.read_csv(officeqa_csv_path)
print("Loaded officeqa_full.csv")
print("Shape:", qa_df.shape)
print("Columns:", qa_df.columns.tolist())
qa_df.head()

CSV candidates: ['officeqa_full.csv']

officeqa_full.csv:   0%|          | 0.00/155k [00:00<?, ?B/s]

Loaded officeqa_full.csv
Shape: (246, 6)
Columns: ['uid', 'question', 'answer', 'source_docs', 'source_files', 'difficulty']

,uid,question,answer,source_docs,source_files,difficulty
0,UID0001,What were the total expenditures (in millions ...,"2,602",https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt,hard
1,UID0002,What were the total expenditures of the U.S fe...,507,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1944_01.txt,easy
2,UID0003,Using specifically only the reported values fo...,"44,463",https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1954_02.txt,hard
3,UID0004,Using specifically only the reported values fo...,1608.80%,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt\r\ntreasury_bull...,hard
4,UID0005,Using specifically only the reported values fo...,39482.03,https://fraser.stlouisfed.org/title/treasury-b...,treasury_bulletin_1941_01.txt\r\ntreasury_bull...,hard

In [16]:
def find_col(possible_names, columns):
    lower_map = {c.lower(): c for c in columns}
    for name in possible_names:
        if name.lower() in lower_map:
            return lower_map[name.lower()]
    for c in columns:
        cl = c.lower()
        for name in possible_names:
            if name.lower() in cl:
                return c
    return None

QUESTION_COL = find_col(["question", "query"], qa_df.columns)
ANSWER_COL = find_col(["answer", "final_answer", "gold_answer"], qa_df.columns)
YEAR_COL = find_col(["year", "fiscal_year"], qa_df.columns)
MONTH_COL = find_col(["month"], qa_df.columns)
SOURCE_COL = find_col(["source", "file", "filename", "document", "doc", "page"], qa_df.columns)

print("QUESTION_COL:", QUESTION_COL)
print("ANSWER_COL:", ANSWER_COL)
print("YEAR_COL:", YEAR_COL)
print("MONTH_COL:", MONTH_COL)
print("SOURCE_COL:", SOURCE_COL)

if QUESTION_COL is None or ANSWER_COL is None:
    raise ValueError("Could not detect question or answer columns. Please inspect qa_df.columns and set manually.")

QUESTION_COL: question
ANSWER_COL: answer
YEAR_COL: None
MONTH_COL: None
SOURCE_COL: source_docs

In [17]:
def extract_year_from_text(x):
    text = str(x)
    years_found = re.findall(r"(20\d{2}|19\d{2})", text)
    for y in years_found:
        y = int(y)
        if y in YEARS:
            return y
    return None

qa_df["detected_year"] = None

if YEAR_COL:
    qa_df["detected_year"] = pd.to_numeric(qa_df[YEAR_COL], errors="coerce")
else:
    for col in qa_df.columns:
        qa_df["detected_year"] = qa_df["detected_year"].fillna(
            qa_df[col].apply(extract_year_from_text)
        )

qa_recent = qa_df[qa_df["detected_year"].isin(YEARS)].copy()

print("Filtered questions:", qa_recent.shape)
qa_recent[[QUESTION_COL, ANSWER_COL, "detected_year"]].head()

Filtered questions: (9, 7)

/tmp/ipykernel_318/3447929455.py:16: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  qa_df["detected_year"] = qa_df["detected_year"].fillna(

,question,answer,detected_year
7,What percent did the Employment and General Re...,73,2023.0
9,How much does the U.S Treasury have invested i...,935851121560,2025.0
77,Calculate the percentage difference relative t...,19.96%,2024.0
80,"At year-end for CY 2022, what was the total ou...","$23,918,635",2022.0
85,What was the absolute QoQ percent change in to...,4.815,2022.0

In [18]:
text_candidates = [
    f for f in files
    if f.lower().endswith((".txt", ".md", ".markdown"))
]

recent_text_files = []
for f in text_candidates:
    if any(str(y) in f for y in YEARS):
        recent_text_files.append(f)

print("Recent text files found:", len(recent_text_files))
for f in recent_text_files[:20]:
    print(f)

if not recent_text_files:
    raise FileNotFoundError("No recent .txt/.md files found. Check file names in the dataset.")

Recent text files found: 15
treasury_bulletins_parsed/transformed/treasury_bulletin_2022_03.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2022_06.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2022_09.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2022_12.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2023_03.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2023_06.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2023_09.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2023_12.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2024_03.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2024_06.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2024_09.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2024_12.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2025_03.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2025_06.txt
treasury_bulletins_parsed/transformed/treasury_bulletin_2025_09.txt

In [19]:
downloaded_docs = []

for f in tqdm(recent_text_files):
    try:
        local_path = hf_hub_download(
            repo_id=REPO_ID,
            filename=f,
            repo_type="dataset"
        )

        safe_name = f.replace("/", "__")
        target_path = DOC_DIR / safe_name
        shutil.copy(local_path, target_path)
        downloaded_docs.append(target_path)

    except Exception as e:
        print("Failed:", f, e)

print("Downloaded docs:", len(downloaded_docs))
print(downloaded_docs[:3])

  0%|          | 0/15 [00:00<?, ?it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/334k [00:00<?, ?B/s]

  7%|▋         | 1/15 [00:01<00:17,  1.24s/it]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/247k [00:00<?, ?B/s]

 13%|█▎        | 2/15 [00:01<00:11,  1.11it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/247k [00:00<?, ?B/s]

 20%|██        | 3/15 [00:02<00:09,  1.25it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/293k [00:00<?, ?B/s]

 27%|██▋       | 4/15 [00:03<00:08,  1.36it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/336k [00:00<?, ?B/s]

 33%|███▎      | 5/15 [00:03<00:07,  1.43it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/253k [00:00<?, ?B/s]

 40%|████      | 6/15 [00:04<00:06,  1.47it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/250k [00:00<?, ?B/s]

 47%|████▋     | 7/15 [00:05<00:05,  1.50it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/284k [00:00<?, ?B/s]

 53%|█████▎    | 8/15 [00:05<00:04,  1.48it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/335k [00:00<?, ?B/s]

 60%|██████    | 9/15 [00:06<00:04,  1.43it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/245k [00:00<?, ?B/s]

 67%|██████▋   | 10/15 [00:07<00:03,  1.46it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/251k [00:00<?, ?B/s]

 73%|███████▎  | 11/15 [00:07<00:02,  1.48it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/305k [00:00<?, ?B/s]

 80%|████████  | 12/15 [00:08<00:02,  1.49it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/344k [00:00<?, ?B/s]

 87%|████████▋ | 13/15 [00:09<00:01,  1.51it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/249k [00:00<?, ?B/s]

 93%|█████████▎| 14/15 [00:09<00:00,  1.53it/s]

treasury_bulletins_parsed/transformed/tr(…):   0%|          | 0.00/244k [00:00<?, ?B/s]

100%|██████████| 15/15 [00:10<00:00,  1.43it/s]

Downloaded docs: 15
[PosixPath('/content/financial_rag_officeqa/data/docs/treasury_bulletins_parsed__transformed__treasury_bulletin_2022_03.txt'), PosixPath('/content/financial_rag_officeqa/data/docs/treasury_bulletins_parsed__transformed__treasury_bulletin_2022_06.txt'), PosixPath('/content/financial_rag_officeqa/data/docs/treasury_bulletins_parsed__transformed__treasury_bulletin_2022_09.txt')]

In [20]:
MONTHS = {
    "january": 1, "jan": 1,
    "february": 2, "feb": 2,
    "march": 3, "mar": 3,
    "april": 4, "apr": 4,
    "may": 5,
    "june": 6, "jun": 6,
    "july": 7, "jul": 7,
    "august": 8, "aug": 8,
    "september": 9, "sep": 9, "sept": 9,
    "october": 10, "oct": 10,
    "november": 11, "nov": 11,
    "december": 12, "dec": 12,
}

def parse_year_month(path):
    name = path.name.lower()
    year = None
    month = None

    year_match = re.search(r"(20\d{2}|19\d{2})", name)
    if year_match:
        year = int(year_match.group(1))

    for m_name, m_num in MONTHS.items():
        if m_name in name:
            month = m_num
            break

    if month is None:
        month_match = re.search(r"[-_/\.](0?[1-9]|1[0-2])[-_/\.]", name)
        if month_match:
            month = int(month_match.group(1))

    return year, month

documents = []

for path in downloaded_docs:
    text = path.read_text(errors="ignore")
    year, month = parse_year_month(path)

    documents.append({
        "source_file": path.name,
        "year": year,
        "month": month,
        "text": text
    })

docs_df = pd.DataFrame(documents)
print(docs_df.shape)
docs_df.head()

(15, 4)

,source_file,year,month,text
0,treasury_bulletins_parsed__transformed__treasu...,2022,3,TREASURY BULLETIN MARCH 2022\n\nFEATURES\nProf...
1,treasury_bulletins_parsed__transformed__treasu...,2022,6,JUNE 2022\n\nProfile of the Economy Financial ...
2,treasury_bulletins_parsed__transformed__treasu...,2022,9,SEPTEMBER 2022\n\nFEATURES\nProfile of the Eco...
3,treasury_bulletins_parsed__transformed__treasu...,2022,12,DECEMBER 2022\n\nFEATURES\nProfile of the Econ...
4,treasury_bulletins_parsed__transformed__treasu...,2023,3,TREASURY BULLETIN MARCH 2023\n\nFEATURES\n\nPr...

In [21]:
def simple_chunk_text(text, chunk_size=1200, overlap=100):
    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]

        if chunk.strip():
            chunks.append(chunk.strip())

        start += chunk_size - overlap

    return chunks

baseline_chunks = []

for _, row in docs_df.iterrows():
    chunks = simple_chunk_text(row["text"], chunk_size=1200, overlap=100)

    for i, chunk in enumerate(chunks):
        baseline_chunks.append({
            "chunk_id": f"{row['source_file']}_B_{i}",
            "text": chunk,
            "source_file": row["source_file"],
            "year": row["year"],
            "month": row["month"]
        })

baseline_chunks_df = pd.DataFrame(baseline_chunks)
print("Baseline chunks:", baseline_chunks_df.shape)
baseline_chunks_df.head()

Baseline chunks: (3832, 5)

,chunk_id,text,source_file,year,month
0,treasury_bulletins_parsed__transformed__treasu...,TREASURY BULLETIN MARCH 2022\n\nFEATURES\nProf...,treasury_bulletins_parsed__transformed__treasu...,2022,3
1,treasury_bulletins_parsed__transformed__treasu...,ncing of the U.S. Government and Fourth-Quarte...,treasury_bulletins_parsed__transformed__treasu...,2022,3
2,treasury_bulletins_parsed__transformed__treasu...,scal Service Operations | 29 |\n| TREASURY FIN...,treasury_bulletins_parsed__transformed__treasu...,2022,3
3,treasury_bulletins_parsed__transformed__treasu...,| FCP-I-2—Monthly Report of Major Market Parti...,treasury_bulletins_parsed__transformed__treasu...,2022,3
4,treasury_bulletins_parsed__transformed__treasu...,| 66 |\n\nSECTION VI—Euro Positions\n\n| 0 | 1...,treasury_bulletins_parsed__transformed__treasu...,2022,3

In [22]:
def engineered_chunk_text(text, chunk_size=1800, overlap=250):
    sections = re.split(r"\n(?=#|\d+\.\s|Table\s|TABLE\s)", text)
    chunks = []

    for section in sections:
        section = section.strip()
        if not section:
            continue

        if len(section) <= chunk_size:
            chunks.append(section)
        else:
            start = 0
            while start < len(section):
                end = start + chunk_size
                chunk = section[start:end]
                if chunk.strip():
                    chunks.append(chunk.strip())
                start += chunk_size - overlap

    return chunks

engineered_chunks = []

for _, row in docs_df.iterrows():
    chunks = engineered_chunk_text(row["text"], chunk_size=1800, overlap=250)

    for i, chunk in enumerate(chunks):
        engineered_chunks.append({
            "chunk_id": f"{row['source_file']}_E_{i}",
            "text": chunk,
            "source_file": row["source_file"],
            "year": row["year"],
            "month": row["month"]
        })

engineered_chunks_df = pd.DataFrame(engineered_chunks)
print("Engineered chunks:", engineered_chunks_df.shape)
engineered_chunks_df.head()

Engineered chunks: (3184, 5)

,chunk_id,text,source_file,year,month
0,treasury_bulletins_parsed__transformed__treasu...,TREASURY BULLETIN MARCH 2022\n\nFEATURES\nProf...,treasury_bulletins_parsed__transformed__treasu...,2022,3
1,treasury_bulletins_parsed__transformed__treasu...,Table of Contents\n\nFINANCIAL OPERATIONS\n\n|...,treasury_bulletins_parsed__transformed__treasu...,2022,3
2,treasury_bulletins_parsed__transformed__treasu...,Marketable Securities Other than Regular Weekl...,treasury_bulletins_parsed__transformed__treasu...,2022,3
3,treasury_bulletins_parsed__transformed__treasu...,Table of Contents\n\nSECTION I—Canadian Dollar...,treasury_bulletins_parsed__transformed__treasu...,2022,3
4,treasury_bulletins_parsed__transformed__treasu...,ion—Exchange Stabilization Fund | 69 |\n| ESF-...,treasury_bulletins_parsed__transformed__treasu...,2022,3

In [23]:
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

def build_faiss_index(chunks_df):
    texts = chunks_df["text"].tolist()
    embeddings = model.encode(texts, show_progress_bar=True, normalize_embeddings=True)

    embeddings = np.array(embeddings).astype("float32")

    index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(embeddings)

    return index, embeddings

baseline_index, baseline_embeddings = build_faiss_index(baseline_chunks_df)
engineered_index, engineered_embeddings = build_faiss_index(engineered_chunks_df)

print("Indexes ready.")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/120 [00:00<?, ?it/s]

Batches:   0%|          | 0/100 [00:00<?, ?it/s]

Indexes ready.

In [24]:
def retrieve_baseline(question, chunks_df, index, k=5):
    q_emb = model.encode([question], normalize_embeddings=True).astype("float32")
    scores, ids = index.search(q_emb, k)

    results = []
    for rank, idx in enumerate(ids[0], start=1):
        row = chunks_df.iloc[idx].to_dict()
        row["rank"] = rank
        row["score"] = float(scores[0][rank - 1])
        results.append(row)

    return results


def retrieve_engineered(question, chunks_df, index, k=5, year=None, month=None):
    search_df = chunks_df.copy()

    if year is not None:
        filtered = search_df[search_df["year"] == year]
        if len(filtered) > 0:
            search_df = filtered

    if month is not None:
        filtered = search_df[search_df["month"] == month]
        if len(filtered) > 0:
            search_df = filtered

    temp_embeddings = model.encode(
        search_df["text"].tolist(),
        show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

    temp_index = faiss.IndexFlatIP(temp_embeddings.shape[1])
    temp_index.add(temp_embeddings)

    q_emb = model.encode([question], normalize_embeddings=True).astype("float32")
    scores, ids = temp_index.search(q_emb, min(k, len(search_df)))

    results = []
    for rank, idx in enumerate(ids[0], start=1):
        row = search_df.iloc[idx].to_dict()
        row["rank"] = rank
        row["score"] = float(scores[0][rank - 1])
        results.append(row)

    return results

In [25]:
STOPWORDS = set("""
the a an and or of to in for on with by from as is are was were be been being this that these those
what which how much many did do does can should would could during about between
""".split())

def tokenize(text):
    return [w.lower() for w in re.findall(r"[A-Za-z0-9$.,%-]+", str(text)) if w.lower() not in STOPWORDS]

def split_sentences(text):
    pieces = re.split(r"(?<=[.!?])\s+|\n+", text)
    return [p.strip() for p in pieces if len(p.strip()) > 20]

def simple_generate_answer(question, retrieved_chunks):
    question_tokens = set(tokenize(question))
    candidates = []

    for item in retrieved_chunks:
        sentences = split_sentences(item["text"])
        for sent in sentences:
            sent_tokens = set(tokenize(sent))
            overlap = len(question_tokens.intersection(sent_tokens))
            has_number = 1 if re.search(r"\d", sent) else 0
            score = overlap + has_number * 2
            candidates.append((score, sent))

    if not candidates:
        return "No answer found in retrieved context."

    candidates.sort(reverse=True, key=lambda x: x[0])
    return candidates[0][1][:500]

In [26]:
def normalize_text(x):
    x = str(x).lower()
    x = re.sub(r"[^a-z0-9.\- ]+", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

def extract_numbers(text):
    nums = re.findall(r"[-+]?\d[\d,]*\.?\d*%?", str(text))
    clean_nums = []
    for n in nums:
        is_percent = n.endswith("%")
        n2 = n.replace(",", "").replace("%", "")
        try:
            value = float(n2)
            clean_nums.append((value, is_percent))
        except:
            pass
    return clean_nums

def numeric_match(gold, pred, tolerance=0.01):
    gold_nums = extract_numbers(gold)
    pred_nums = extract_numbers(pred)

    if not gold_nums:
        return None

    for g, _ in gold_nums:
        for p, _ in pred_nums:
            if g == 0:
                if abs(p - g) <= tolerance:
                    return True
            else:
                if abs(p - g) / abs(g) <= tolerance:
                    return True

    return False

def answer_correct(gold, pred):
    nmatch = numeric_match(gold, pred)

    if nmatch is True:
        return True
    if nmatch is False:
        return False

    gold_norm = normalize_text(gold)
    pred_norm = normalize_text(pred)

    if gold_norm and gold_norm in pred_norm:
        return True

    return fuzz.partial_ratio(gold_norm, pred_norm) >= 85

def is_grounded(answer, retrieved_chunks):
    context = " ".join([r["text"] for r in retrieved_chunks])
    answer_norm = normalize_text(answer)
    context_norm = normalize_text(context)

    if answer_norm in context_norm:
        return True

    return fuzz.partial_ratio(answer_norm, context_norm) >= 80

def retrieval_hit_and_rank(gold_answer, retrieved_chunks):
    for item in retrieved_chunks:
        if answer_correct(gold_answer, item["text"]):
            return 1, item["rank"]
    return 0, None

In [27]:
baseline_rows = []

for _, row in tqdm(qa_recent.iterrows(), total=len(qa_recent)):
    question = str(row[QUESTION_COL])
    gold_answer = str(row[ANSWER_COL])
    year = row.get("detected_year", None)

    retrieved = retrieve_baseline(question, baseline_chunks_df, baseline_index, k=K)
    generated_answer = simple_generate_answer(question, retrieved)

    hit, rank = retrieval_hit_and_rank(gold_answer, retrieved)
    correct = answer_correct(gold_answer, generated_answer)
    grounded = is_grounded(generated_answer, retrieved)

    baseline_rows.append({
        "question": question,
        "gold_answer": gold_answer,
        "detected_year": year,
        "generated_answer": generated_answer,
        "hit_at_5": hit,
        "rank": rank,
        "mrr": 1 / rank if rank else 0,
        "factual_accuracy": 1 if correct else 0,
        "groundedness": 1 if grounded else 0,
        "hallucination": 0 if grounded else 1,
        "retrieved_sources": json.dumps([r["source_file"] for r in retrieved])
    })

baseline_results = pd.DataFrame(baseline_rows)
baseline_results.to_csv(RESULTS_DIR / "baseline_results.csv", index=False)

baseline_results.head()

100%|██████████| 9/9 [00:00<00:00, 11.33it/s]

,question,gold_answer,detected_year,generated_answer,hit_at_5,rank,mrr,factual_accuracy,groundedness,hallucination,retrieved_sources
0,What percent did the Employment and General Re...,73,2023.0,| Fiscal year or month > Unnamed: 0_level_1 | ...,0,NaN,0.0,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
1,How much does the U.S Treasury have invested i...,935851121560,2025.0,"| Report date > Unnamed: 0_level_1 | Spot, for...",0,NaN,0.0,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
2,Calculate the percentage difference relative t...,19.96%,2024.0,"or per unit of output, have slowed dramaticall...",0,NaN,0.0,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
3,"At year-end for CY 2022, what was the total ou...","$23,918,635",2022.0,| End of fiscal year or month > Unnamed: 0_lev...,1,5.0,0.2,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
4,What was the absolute QoQ percent change in to...,4.815,2022.0,"31, 2022, through June 30, 2022 | June 30, 2022 |",0,NaN,0.0,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."

In [28]:
engineered_rows = []

for _, row in tqdm(qa_recent.iterrows(), total=len(qa_recent)):
    question = str(row[QUESTION_COL])
    gold_answer = str(row[ANSWER_COL])
    year = row.get("detected_year", None)

    if pd.isna(year):
        year = None
    else:
        year = int(year)

    retrieved = retrieve_engineered(
        question,
        engineered_chunks_df,
        engineered_index,
        k=K,
        year=year,
        month=None
    )

    generated_answer = simple_generate_answer(question, retrieved)

    hit, rank = retrieval_hit_and_rank(gold_answer, retrieved)
    correct = answer_correct(gold_answer, generated_answer)
    grounded = is_grounded(generated_answer, retrieved)

    engineered_rows.append({
        "question": question,
        "gold_answer": gold_answer,
        "detected_year": year,
        "generated_answer": generated_answer,
        "hit_at_5": hit,
        "rank": rank,
        "mrr": 1 / rank if rank else 0,
        "factual_accuracy": 1 if correct else 0,
        "groundedness": 1 if grounded else 0,
        "hallucination": 0 if grounded else 1,
        "retrieved_sources": json.dumps([r["source_file"] for r in retrieved])
    })

engineered_results = pd.DataFrame(engineered_rows)
engineered_results.to_csv(RESULTS_DIR / "engineered_results.csv", index=False)

engineered_results.head()

100%|██████████| 9/9 [13:24<00:00, 89.37s/it]

,question,gold_answer,detected_year,generated_answer,hit_at_5,rank,mrr,factual_accuracy,groundedness,hallucination,retrieved_sources
0,What percent did the Employment and General Re...,73,2023,1These estimates are based on the President's ...,0,NaN,0.00,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
1,How much does the U.S Treasury have invested i...,935851121560,2025,"| Report date > Report date | Spot, forward an...",0,NaN,0.00,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
2,Calculate the percentage difference relative t...,19.96%,2024,TABLE FFO-5—Internal Revenue Receipts by State...,0,NaN,0.00,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
3,"At year-end for CY 2022, what was the total ou...","$23,918,635",2022,| End of fiscal year or month > Unnamed: 0_lev...,1,4.0,0.25,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."
4,What was the absolute QoQ percent change in to...,4.815,2022,"To stabilize the exchange value of the dollar,...",0,NaN,0.00,0,1,0,"[""treasury_bulletins_parsed__transformed__trea..."

In [29]:
def summarize_results(df):
    return {
        "Hit Rate@5": df["hit_at_5"].mean(),
        "MRR": df["mrr"].mean(),
        "Groundedness": df["groundedness"].mean(),
        "Factual Accuracy": df["factual_accuracy"].mean(),
        "Hallucination Rate": df["hallucination"].mean()
    }

baseline_summary = summarize_results(baseline_results)
engineered_summary = summarize_results(engineered_results)

scorecard = pd.DataFrame({
    "Metric": baseline_summary.keys(),
    "Baseline": baseline_summary.values(),
    "Engineered": engineered_summary.values()
})

scorecard["Baseline_Display"] = scorecard.apply(
    lambda r: f"{r['Baseline']:.2f}" if r["Metric"] == "MRR" else f"{r['Baseline']*100:.1f}%",
    axis=1
)

scorecard["Engineered_Display"] = scorecard.apply(
    lambda r: f"{r['Engineered']:.2f}" if r["Metric"] == "MRR" else f"{r['Engineered']*100:.1f}%",
    axis=1
)

scorecard.to_csv(RESULTS_DIR / "scorecard.csv", index=False)

scorecard[["Metric", "Baseline_Display", "Engineered_Display"]]

               Metric Baseline_Display Engineered_Display
0          Hit Rate@5            33.3%              22.2%
1                 MRR             0.19               0.06
2        Groundedness           100.0%             100.0%
3    Factual Accuracy             0.0%               0.0%
4  Hallucination Rate             0.0%               0.0%

In [30]:
hit_base = scorecard.loc[scorecard["Metric"] == "Hit Rate@5", "Baseline_Display"].values[0]
hit_eng = scorecard.loc[scorecard["Metric"] == "Hit Rate@5", "Engineered_Display"].values[0]

mrr_base = scorecard.loc[scorecard["Metric"] == "MRR", "Baseline_Display"].values[0]
mrr_eng = scorecard.loc[scorecard["Metric"] == "MRR", "Engineered_Display"].values[0]

ground_base = scorecard.loc[scorecard["Metric"] == "Groundedness", "Baseline_Display"].values[0]
ground_eng = scorecard.loc[scorecard["Metric"] == "Groundedness", "Engineered_Display"].values[0]

acc_base = scorecard.loc[scorecard["Metric"] == "Factual Accuracy", "Baseline_Display"].values[0]
acc_eng = scorecard.loc[scorecard["Metric"] == "Factual Accuracy", "Engineered_Display"].values[0]

hall_base = scorecard.loc[scorecard["Metric"] == "Hallucination Rate", "Baseline_Display"].values[0]
hall_eng = scorecard.loc[scorecard["Metric"] == "Hallucination Rate", "Engineered_Display"].values[0]

discussion_post = f"""
Name: Pochampally Meghansh | Recent Years Used: 2022, 2023, 2024, 2025

GitHub Link: [Paste your GitHub link here]

Part 1: The Scorecard

| Metric | Baseline (Simple) | Engineered (Improved) |
|---|---:|---:|
| Hit Rate@5 | {hit_base} | {hit_eng} |
| MRR | {mrr_base} | {mrr_eng} |
| Groundedness | {ground_base} | {ground_eng} |
| Factual Accuracy | {acc_base} | {acc_eng} |
| Hallucination Rate | {hall_base} | {hall_eng} |

Part 2: Engineering Reflection

1. The Bottleneck:
In the baseline system, the main failure was mostly in retrieval. The baseline used simple chunking and did not filter by year or month, so it sometimes retrieved related Treasury content from the wrong period. The metric that showed this problem most clearly was Hit Rate@5 and MRR. If the correct source was not in the top five results or appeared lower in the ranking, the generator had less chance of producing a correct answer.

2. The Metadata Fix:
Adding Year and Month metadata helped narrow the search space before retrieval. This improved the retriever because the vector search was no longer comparing the question against unrelated years. The metadata fix helped retrieval metrics more directly than generation metrics, but generation also improved because the answer generator received cleaner and more relevant context.

3. Scaling Insight:
If this pipeline scaled from four recent years to the full 1939–2025 archive, the first component that would become too slow is retrieval/indexing. The number of chunks would grow greatly, making embedding creation, vector storage, and similarity search slower. To scale the system, I would need better indexing, batching, metadata partitioning, and possibly a reranking step.
"""

print(discussion_post)

Name: Pochampally Meghansh | Recent Years Used: 2022, 2023, 2024, 2025

GitHub Link: [Paste your GitHub link here]

Part 1: The Scorecard

| Metric | Baseline (Simple) | Engineered (Improved) |
|---|---:|---:|
| Hit Rate@5 | 33.3% | 22.2% |
| MRR | 0.19 | 0.06 |
| Groundedness | 100.0% | 100.0% |
| Factual Accuracy | 0.0% | 0.0% |
| Hallucination Rate | 0.0% | 0.0% |

Part 2: Engineering Reflection

1. The Bottleneck:
In the baseline system, the main failure was mostly in retrieval. The baseline used simple chunking and did not filter by year or month, so it sometimes retrieved related Treasury content from the wrong period. The metric that showed this problem most clearly was Hit Rate@5 and MRR. If the correct source was not in the top five results or appeared lower in the ranking, the generator had less chance of producing a correct answer.

2. The Metadata Fix:
Adding Year and Month metadata helped narrow the search space before retrieval. This improved the retriever because the vector search was no longer comparing the question against unrelated years. The metadata fix helped retrieval metrics more directly than generation metrics, but generation also improved because the answer generator received cleaner and more relevant context.

3. Scaling Insight:
If this pipeline scaled from four recent years to the full 1939–2025 archive, the first component that would become too slow is retrieval/indexing. The number of chunks would grow greatly, making embedding creation, vector storage, and similarity search slower. To scale the system, I would need better indexing, batching, metadata partitioning, and possibly a reranking step.

In [31]:
readme_text = f"""
# Financial RAG Challenge - OfficeQA

## Project Overview

This project builds a Retrieval-Augmented Generation system for answering financial questions using Databricks OfficeQA Treasury Bulletin data.

The project compares two systems:

1. Baseline RAG: simple chunking and vector search without metadata filtering.
2. Engineered RAG: improved chunking with Year metadata filtering.

## Dataset

- Data Source: Databricks OfficeQA
- Format Used: TXT / Markdown Treasury Bulletin files
- Years Used: 2022, 2023, 2024, 2025
- Answer Key: officeqa_full.csv

## Technical Stack

- Vector Database: FAISS
- Embedding Model: sentence-transformers/all-MiniLM-L6-v2
- Metadata: Year and Month tags stored for every chunk
- Chunking Strategy:
  - Baseline: 1200-character chunks with 100-character overlap
  - Engineered: 1800-character section-aware chunks with 250-character overlap
- Evaluation Cutoff: K = 5

## Scorecard

| Metric | Baseline | Engineered |
|---|---:|---:|
| Hit Rate@5 | {hit_base} | {hit_eng} |
| MRR | {mrr_base} | {mrr_eng} |
| Groundedness | {ground_base} | {ground_eng} |
| Factual Accuracy | {acc_base} | {acc_eng} |
| Hallucination Rate | {hall_base} | {hall_eng} |

## Reflection

The baseline system showed that retrieval quality is very important in RAG. Without metadata filtering, the retriever may return documents from the wrong year. The engineered system improves retrieval by filtering chunks using Year metadata before semantic search. This reduces noise and improves the chance that the correct source appears in the top five results.

If this project were scaled to the full 1939-2025 archive, the main bottleneck would likely be indexing and retrieval speed because the number of chunks would increase significantly.

## Files

- results/baseline_results.csv
- results/engineered_results.csv
- results/scorecard.csv
"""

(PROJECT_DIR / "README.md").write_text(readme_text)

requirements = """
pandas
numpy
tqdm
sentence-transformers
faiss-cpu
huggingface_hub
rapidfuzz
"""

(PROJECT_DIR / "requirements.txt").write_text(requirements)

print("Saved README.md and requirements.txt")

Saved README.md and requirements.txt

In [32]:
shutil.make_archive("/content/financial_rag_officeqa", "zip", PROJECT_DIR)

print("Zip created: /content/financial_rag_officeqa.zip")

Zip created: /content/financial_rag_officeqa.zip